name: Build & Release

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build app
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: docker build -t tasktrackerapp:${{ github.sha }} .

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: tasktrackerapp:${{ github.sha }}
          format: table
          severity: HIGH,CRITICAL
          exit-code: 1

      - name: Scan image (FAIL on HIGH/CRITICAL)
        run: |
          trivy image --severity HIGH,CRITICAL --exit-code 1 tasktrackerapp:${{ github.sha }}